services:
- mysql

variables:
  MYSQL_DATABASE: Cover_Me
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_HOST: localhost
  MYSQL_PORT : 3306

connect:
  image: mysql
  script:
  - echo "SELECT 'OK';" | mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --host="$MYSQL_HOST" --port="$MYSQL_PORT" "$MYSQL_DATABASE"

stages: 
  ['test']
test:
  image: python:3.7
  stage: test
  only:
    ['develop']
  when:
    on_success
  script: 
    - pip install pytest
    - pip install pytest-dependency
    - pip install jupyter_core
    - pip install jupyter_client
    - pip install bcrypt
    - pip install mysql-connector-python
    - pytest src/test_rs.py --verbose --color=yes
    - pytest src/test_login_register.py --verbose --color=yes
    - pytest src/test_pesanan.py --verbose --color=yes
    - pytest src/test_suhu.py --verbose --color=yes
    - pytest src/test_laporan.py --verbose --color=yes