# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_UpdateLaporan.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from update_laporan import *

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(900, 600)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.Sidebar = QtWidgets.QFrame(self.centralwidget)
                self.Sidebar.setGeometry(QtCore.QRect(0, 0, 211, 611))
                self.Sidebar.setStyleSheet("QFrame{\n"
                "    background-color: rgb(72, 67, 67);\n"
                "}")
                self.Sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.Sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
                self.Sidebar.setObjectName("Sidebar")
                self.Laporan_Harian = QtWidgets.QPushButton(self.Sidebar)
                self.Laporan_Harian.setGeometry(QtCore.QRect(20, 180, 171, 51))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                self.Laporan_Harian.setFont(font)
                self.Laporan_Harian.setStyleSheet("QPushButton{\n"
                "    background-color: rgb(72, 67, 67);\n"
                "    color: rgb(255, 255, 255);\n"
                "}")
                self.Laporan_Harian.setObjectName("Laporan_Harian")
                self.label = QtWidgets.QLabel(self.Sidebar)
                self.label.setGeometry(QtCore.QRect(20, 20, 171, 71))
                font = QtGui.QFont()
                font.setPointSize(28)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setStyleSheet("QLabel{\n"
                "    color: rgb(255, 255, 255);\n"
                "}")
                self.label.setObjectName("label")
                self.RumahSakit = QtWidgets.QPushButton(self.Sidebar)
                self.RumahSakit.setGeometry(QtCore.QRect(20, 250, 171, 51))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                self.RumahSakit.setFont(font)
                self.RumahSakit.setStyleSheet("QPushButton{\n"
                "    background-color: rgb(72, 67, 67);\n"
                "    color: rgb(255, 255, 255);\n"
                "}")
                self.RumahSakit.setObjectName("RumahSakit")
                self.Daftar_Pesanan = QtWidgets.QPushButton(self.Sidebar)
                self.Daftar_Pesanan.setGeometry(QtCore.QRect(20, 320, 171, 51))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                self.Daftar_Pesanan.setFont(font)
                self.Daftar_Pesanan.setStyleSheet("QPushButton{\n"
                "    background-color: rgb(72, 67, 67);\n"
                "    color: rgb(255, 255, 255);\n"
                "}")
                self.Daftar_Pesanan.setObjectName("Daftar_Pesanan")
                self.Home = QtWidgets.QPushButton(self.Sidebar)
                self.Home.setGeometry(QtCore.QRect(20, 110, 171, 51))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                self.Home.setFont(font)
                self.Home.setStyleSheet("QPushButton{\n"
                "    background-color: rgb(72, 67, 67);\n"
                "    color: rgb(255, 255, 255);\n"
                "}")
                self.Home.setObjectName("Home")
                self.Logout = QtWidgets.QPushButton(self.Sidebar)
                self.Logout.setGeometry(QtCore.QRect(20, 520, 171, 51))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                self.Logout.setFont(font)
                self.Logout.setStyleSheet("QPushButton{\n"
                "    background-color: rgb(72, 67, 67);\n"
                "    color: rgb(255, 255, 255);\n"
                "}")
                self.Logout.setObjectName("Logout")
                self.Nama_Admin = QtWidgets.QLabel(self.centralwidget)
                self.Nama_Admin.setGeometry(QtCore.QRect(650, 0, 251, 61))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                self.Nama_Admin.setFont(font)
                self.Nama_Admin.setObjectName("Nama_Admin")
                self.header_tambah = QtWidgets.QLabel(self.centralwidget)
                self.header_tambah.setGeometry(QtCore.QRect(355, 90, 401, 31))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.header_tambah.setFont(font)
                self.header_tambah.setStyleSheet("QLabel{\n"
                "    color: rgb(0, 0, 0);\n"
                "}")
                self.header_tambah.setObjectName("header_tambah")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(310, 130, 491, 281))
                self.label_2.setText("")
                self.label_2.setPixmap(QtGui.QPixmap("../img/nao.jpg"))
                self.label_2.setScaledContents(True)
                self.label_2.setObjectName("label_2")
                self.edit_positif = QtWidgets.QLineEdit(self.centralwidget)
                self.edit_positif.setEnabled(False)
                self.edit_positif.setGeometry(QtCore.QRect(310, 450, 141, 81))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.edit_positif.setFont(font)
                self.edit_positif.setStyleSheet("border-style: solid;\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-width:1px;\n"
                "border-style: solid;")
                self.edit_positif.setText("")
                self.edit_positif.setAlignment(QtCore.Qt.AlignCenter)
                self.edit_positif.setObjectName("edit_positif")
                self.label_positif = QtWidgets.QLabel(self.centralwidget)
                self.label_positif.setGeometry(QtCore.QRect(310, 425, 141, 21))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(12)
                self.label_positif.setFont(font)
                self.label_positif.setAutoFillBackground(False)
                self.label_positif.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-width:1px;\n"
                "border-style: solid;")
                self.label_positif.setAlignment(QtCore.Qt.AlignCenter)
                self.label_positif.setObjectName("label_positif")
                self.button_edit_positif = QtWidgets.QPushButton(self.centralwidget)
                self.button_edit_positif.setGeometry(QtCore.QRect(428, 452, 21, 21))
                self.button_edit_positif.setAutoFillBackground(False)
                self.button_edit_positif.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.button_edit_positif.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("../img/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.button_edit_positif.setIcon(icon)
                self.button_edit_positif.setObjectName("button_edit_positif")
                self.button_edit_sembuh = QtWidgets.QPushButton(self.centralwidget)
                self.button_edit_sembuh.setGeometry(QtCore.QRect(603, 452, 21, 21))
                self.button_edit_sembuh.setAutoFillBackground(False)
                self.button_edit_sembuh.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.button_edit_sembuh.setText("")
                self.button_edit_sembuh.setIcon(icon)
                self.button_edit_sembuh.setObjectName("button_edit_sembuh")
                self.label_sembuh = QtWidgets.QLabel(self.centralwidget)
                self.label_sembuh.setGeometry(QtCore.QRect(485, 425, 141, 21))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(12)
                self.label_sembuh.setFont(font)
                self.label_sembuh.setAutoFillBackground(False)
                self.label_sembuh.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-width:1px;\n"
                "border-style: solid;")
                self.label_sembuh.setAlignment(QtCore.Qt.AlignCenter)
                self.label_sembuh.setObjectName("label_sembuh")
                self.edit_sembuh = QtWidgets.QLineEdit(self.centralwidget)
                self.edit_sembuh.setEnabled(False)
                self.edit_sembuh.setGeometry(QtCore.QRect(485, 450, 141, 81))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.edit_sembuh.setFont(font)
                self.edit_sembuh.setStyleSheet("border-style: solid;\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-width:1px;\n"
                "border-style: solid;")
                self.edit_sembuh.setText("")
                self.edit_sembuh.setAlignment(QtCore.Qt.AlignCenter)
                self.edit_sembuh.setObjectName("edit_sembuh")
                self.button_edit_meninggal = QtWidgets.QPushButton(self.centralwidget)
                self.button_edit_meninggal.setGeometry(QtCore.QRect(778, 452, 21, 21))
                self.button_edit_meninggal.setAutoFillBackground(False)
                self.button_edit_meninggal.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.button_edit_meninggal.setText("")
                self.button_edit_meninggal.setIcon(icon)
                self.button_edit_meninggal.setObjectName("button_edit_meninggal")
                self.edit_meninggal = QtWidgets.QLineEdit(self.centralwidget)
                self.edit_meninggal.setEnabled(False)
                self.edit_meninggal.setGeometry(QtCore.QRect(660, 450, 141, 81))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.edit_meninggal.setFont(font)
                self.edit_meninggal.setStyleSheet("border-style: solid;\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-width:1px;\n"
                "border-style: solid;")
                self.edit_meninggal.setText("")
                self.edit_meninggal.setAlignment(QtCore.Qt.AlignCenter)
                self.edit_meninggal.setObjectName("edit_meninggal")
                self.label_meninggal = QtWidgets.QLabel(self.centralwidget)
                self.label_meninggal.setGeometry(QtCore.QRect(660, 425, 141, 21))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(12)
                self.label_meninggal.setFont(font)
                self.label_meninggal.setAutoFillBackground(False)
                self.label_meninggal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "border-color: rgb(0, 0, 0);\n"
                "border-width:1px;\n"
                "border-style: solid;")
                self.label_meninggal.setAlignment(QtCore.Qt.AlignCenter)
                self.label_meninggal.setObjectName("label_meninggal")
                self.button_simpan_positif = QtWidgets.QPushButton(self.centralwidget)
                self.button_simpan_positif.setEnabled(True)
                self.button_simpan_positif.setGeometry(QtCore.QRect(310, 531, 141, 23))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(10)
                self.button_simpan_positif.setFont(font)
                self.button_simpan_positif.setStyleSheet("background-color: rgb(0, 255, 0);")
                self.button_simpan_positif.setObjectName("button_simpan_positif")
                self.button_simpan_sembuh = QtWidgets.QPushButton(self.centralwidget)
                self.button_simpan_sembuh.setEnabled(True)
                self.button_simpan_sembuh.setGeometry(QtCore.QRect(485, 531, 141, 23))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(10)
                self.button_simpan_sembuh.setFont(font)
                self.button_simpan_sembuh.setStyleSheet("background-color: rgb(0, 255, 0);")
                self.button_simpan_sembuh.setObjectName("button_simpan_sembuh")
                self.button_simpan_meninggal = QtWidgets.QPushButton(self.centralwidget)
                self.button_simpan_meninggal.setEnabled(True)
                self.button_simpan_meninggal.setGeometry(QtCore.QRect(660, 531, 141, 23))
                font = QtGui.QFont()
                font.setFamily("Roboto")
                font.setPointSize(10)
                self.button_simpan_meninggal.setFont(font)
                self.button_simpan_meninggal.setStyleSheet("background-color: rgb(0, 255, 0);")
                self.button_simpan_meninggal.setObjectName("button_simpan_meninggal")
                self.Sidebar.raise_()
                self.Nama_Admin.raise_()
                self.header_tambah.raise_()
                self.label_2.raise_()
                self.edit_positif.raise_()
                self.label_positif.raise_()
                self.button_edit_positif.raise_()
                self.label_sembuh.raise_()
                self.edit_sembuh.raise_()
                self.button_edit_sembuh.raise_()
                self.edit_meninggal.raise_()
                self.label_meninggal.raise_()
                self.button_edit_meninggal.raise_()
                self.button_simpan_positif.raise_()
                self.button_simpan_sembuh.raise_()
                self.button_simpan_meninggal.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                # Melakukan setup SQL
                self.setupSql()

                # Hide Simpan
                self.hideAllSimpan()

                # connect button
                self.button_edit_positif.clicked.connect(self.enableKasusPositif)
                self.button_edit_sembuh.clicked.connect(self.enablePasienSembuh)
                self.button_edit_meninggal.clicked.connect(self.enablePasienMeninggal)
                self.button_simpan_positif.clicked.connect(self.simpanKasusPositif)
                self.button_simpan_sembuh.clicked.connect(self.simpanPasienSembuh)
                self.button_simpan_meninggal.clicked.connect(self.simpanPasienMeninggal)

                # Set Initial Value
                self.refreshAllValue()

        
                
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.Laporan_Harian.setText(_translate("MainWindow", "Laporan Harian"))
                self.label.setText(_translate("MainWindow", "CoverMe"))
                self.RumahSakit.setText(_translate("MainWindow", "Rumah Sakit"))
                self.Daftar_Pesanan.setText(_translate("MainWindow", "Daftar Pesanan"))
                self.Home.setText(_translate("MainWindow", "Home"))
                self.Logout.setText(_translate("MainWindow", "Logout"))
                self.Nama_Admin.setText(_translate("MainWindow", "Welcome  <AdminName>"))
                self.header_tambah.setText(_translate("MainWindow", "LAPORAN HARIAN COVID-19"))
                self.label_positif.setText(_translate("MainWindow", "Kasus Positif"))
                self.label_sembuh.setText(_translate("MainWindow", "Pasien Sembuh"))
                self.label_meninggal.setText(_translate("MainWindow", "Pasien Meninggal"))
                self.button_simpan_positif.setText(_translate("MainWindow", "Simpan"))
                self.button_simpan_sembuh.setText(_translate("MainWindow", "Simpan"))
                self.button_simpan_meninggal.setText(_translate("MainWindow", "Simpan"))
	
        def setupSql(self):
		# Melakukan setup koneksi SQL
                config = {
                        "user": "root",
                        "password": "root",
                        "host": "localhost",
                        "port" : "3307"
                }
                self.DB_NAME = 'Cover_Me'
                self.db = mysql.connector.connect(**config)
                self.cursor = self.db.cursor()
        
        def hideAllSimpan(self):
                self.button_simpan_positif.setVisible(False)
                self.button_simpan_sembuh.setVisible(False)
                self.button_simpan_meninggal.setVisible(False)

        def enableKasusPositif(self):
                self.edit_positif.setEnabled(True)
                self.button_simpan_positif.setVisible(True)
        
        def enablePasienSembuh(self):
                self.edit_sembuh.setEnabled(True)
                self.button_simpan_sembuh.setVisible(True)

        def enablePasienMeninggal(self):
                self.edit_meninggal.setEnabled(True)
                self.button_simpan_meninggal.setVisible(True)

        def refreshAllValue(self):
                test = get_kasus_positif(self.cursor, self.DB_NAME)[1][0][0]
                print(test)
                self.edit_positif.setText(str(get_kasus_positif(self.cursor, self.DB_NAME)[1][0][0]))
                self.edit_sembuh.setText(str(get_pasien_sembuh(self.cursor, self.DB_NAME)[1][0][0]))
                self.edit_meninggal.setText(str(get_pasien_meninggal(self.cursor, self.DB_NAME)[1][0][0]))

        def simpanKasusPositif(self):
                new = self.edit_positif.text()
                result = set_kasus_positif(self.db, self.cursor, self.DB_NAME, new)
                if(result[0]==0):
                        self.showAlert(result[1])
                else:
                        self.showSucc(result[1])
                        self.button_simpan_positif.setVisible(False)
                        self.edit_positif.setEnabled(False)
                self.refreshAllValue()
                
        
        def simpanPasienSembuh(self):
                new = self.edit_sembuh.text()
                result = set_pasien_sembuh(self.db, self.cursor, self.DB_NAME, new)
                if(result[0]==0):
                        self.showAlert(result[1])
                else:
                        self.showSucc(result[1])
                        self.button_simpan_sembuh.setVisible(False)
                        self.edit_sembuh.setEnabled(False)
                self.refreshAllValue()


        def simpanPasienMeninggal(self):
                new = self.edit_meninggal.text()
                result = set_pasien_meninggal(self.db, self.cursor, self.DB_NAME, new)
                if(result[0]==0):
                        self.showAlert(result[1])
                else:
                        self.showSucc(result[1])
                        self.button_simpan_meninggal.setVisible(False)
                        self.edit_meninggal.setEnabled(False)
                self.refreshAllValue()


        def showAlert(self,err):
                # Menampilkan pesan kesalahan
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                msg.setText(err)
                x = msg.exec_()
        def showSucc(self,succ):
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setText(succ)
                x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
