# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Pesanan.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from autentikasi import get_username
from PyQt5 import QtCore, QtGui, QtWidgets
from pesanan import *
from rumah_sakit import *
import mysql.connector
from ui_login import *
from Admin_Home import *
from Admin_RS import *
from Admin_UpdateLaporan import *


class Ui_AdminPesananWindow(object):
	def setupUi(self, AdminPesananWindow, ID_Pengguna=1):
		self.AdminPesananWindow = AdminPesananWindow
		AdminPesananWindow.setObjectName("AdminPesananWindow")
		AdminPesananWindow.resize(900, 600)
		self.centralwidget = QtWidgets.QWidget(AdminPesananWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.tabel_pesan = QtWidgets.QTableWidget(self.centralwidget)
		self.tabel_pesan.setGeometry(QtCore.QRect(250, 110, 591, 361))
		self.tabel_pesan.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
		self.tabel_pesan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.tabel_pesan.setColumnCount(6)
		self.tabel_pesan.setObjectName("tabel_pesan")
		self.tabel_pesan.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(5, item)
		self.tabel_pesan.verticalHeader().setVisible(False)
		self.tabel_pesan.verticalHeader().setDefaultSectionSize(30)
		self.header_pesan_2 = QtWidgets.QLabel(self.centralwidget)
		self.header_pesan_2.setGeometry(QtCore.QRect(250, 60, 301, 41))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.header_pesan_2.setFont(font)
		self.header_pesan_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"}")
		self.header_pesan_2.setObjectName("header_pesan_2")
		self.Nama_Admin = QtWidgets.QLabel(self.centralwidget)
		self.Nama_Admin.setGeometry(QtCore.QRect(640, 10, 251, 61))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Nama_Admin.setFont(font)
		self.Nama_Admin.setObjectName("Nama_Admin")
		self.Accept_Button = QtWidgets.QPushButton(self.centralwidget)
		self.Accept_Button.setGeometry(QtCore.QRect(480, 490, 171, 41))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(12)
		self.Accept_Button.setFont(font)
		self.Accept_Button.setStyleSheet("QPushButton{\n"
"    background-color: green;\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.Accept_Button.setObjectName("Accept_Button")
		self.Reject_Button = QtWidgets.QPushButton(self.centralwidget)
		self.Reject_Button.setGeometry(QtCore.QRect(670, 490, 171, 41))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(12)
		self.Reject_Button.setFont(font)
		self.Reject_Button.setStyleSheet("QPushButton{\n"
"    background-color: red;\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.Reject_Button.setObjectName("Reject_Button")
		self.Sidebar = QtWidgets.QFrame(self.centralwidget)
		self.Sidebar.setGeometry(QtCore.QRect(0, 0, 211, 611))
		self.Sidebar.setStyleSheet("QFrame{\n"
"    background-color: rgb(72, 67, 67);\n"
"}")
		self.Sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.Sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
		self.Sidebar.setObjectName("Sidebar")
		self.Laporan_Harian = QtWidgets.QPushButton(self.Sidebar)
		self.Laporan_Harian.setGeometry(QtCore.QRect(20, 180, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Laporan_Harian.setFont(font)
		self.Laporan_Harian.setStyleSheet("QPushButton{\n"
"    background-color: rgb(72, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.Laporan_Harian.setObjectName("Laporan_Harian")
		self.label = QtWidgets.QLabel(self.Sidebar)
		self.label.setGeometry(QtCore.QRect(20, 20, 171, 71))
		font = QtGui.QFont()
		font.setPointSize(28)
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.label.setObjectName("label")
		self.RumahSakit = QtWidgets.QPushButton(self.Sidebar)
		self.RumahSakit.setGeometry(QtCore.QRect(20, 250, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.RumahSakit.setFont(font)
		self.RumahSakit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(72, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.RumahSakit.setObjectName("RumahSakit")
		self.Daftar_Pesanan = QtWidgets.QPushButton(self.Sidebar)
		self.Daftar_Pesanan.setGeometry(QtCore.QRect(20, 320, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Daftar_Pesanan.setFont(font)
		self.Daftar_Pesanan.setStyleSheet("QPushButton{\n"
"    background-color: rgb(72, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.Daftar_Pesanan.setObjectName("Daftar_Pesanan")
		self.Home = QtWidgets.QPushButton(self.Sidebar)
		self.Home.setGeometry(QtCore.QRect(20, 110, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Home.setFont(font)
		self.Home.setStyleSheet("QPushButton{\n"
"    background-color: rgb(72, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.Home.setObjectName("Home")
		self.Logout = QtWidgets.QPushButton(self.Sidebar)
		self.Logout.setGeometry(QtCore.QRect(20, 520, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Logout.setFont(font)
		self.Logout.setStyleSheet("QPushButton{\n"
"    background-color: rgb(72, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
		self.Logout.setObjectName("Logout")
		AdminPesananWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(AdminPesananWindow)
		self.statusbar.setObjectName("statusbar")
		AdminPesananWindow.setStatusBar(self.statusbar)

		#Setup
		self.setupSql()
		self.ID_Pengguna = ID_Pengguna

		#Navigasi
		self.Laporan_Harian.clicked.connect(self.to_update_laporan)
		self.Home.clicked.connect(self.to_Admin_Home)
		self.Logout.clicked.connect(self.logout)
		self.RumahSakit.clicked.connect(self.to_Data_RS)

		self.loadTable()

		self.Accept_Button.clicked.connect(self.acceptPesanan)
		self.Reject_Button.clicked.connect(self.rejectPesanan)

		self.retranslateUi(AdminPesananWindow)
		QtCore.QMetaObject.connectSlotsByName(AdminPesananWindow)


	def setupSql(self):
		# Melakukan setup koneksi SQL
		self.DB_NAME = get_DB_NAME()
		self.db = mysql.connector.connect(**get_config())
		self.cursor = self.db.cursor()

	def loadTable(self):
		self.tabel_pesan.setColumnWidth(0,50)
		self.tabel_pesan.setColumnWidth(1,100)
		self.tabel_pesan.setColumnWidth(2,250)
		self.tabel_pesan.setColumnWidth(3,150)
		self.tabel_pesan.setColumnWidth(4,100)
		self.tabel_pesan.setColumnWidth(5,100)
		res = get_all_pesanan_ongoing(self.cursor,self.DB_NAME)
		if (res[0]==1):
			data = res[1]
			self.tabel_pesan.setRowCount(len(data))
			idx = 0
			for row in data:
				print(row)
				self.tabel_pesan.setItem(idx, 0, QtWidgets.QTableWidgetItem(str(row[0])))
				self.tabel_pesan.setItem(idx, 1, QtWidgets.QTableWidgetItem(str(row[1])))
				list_keadaan = convert_riwayat_to_listofkeadaan(row[2])
				
				self.tabel_pesan.setItem(idx, 2, QtWidgets.QTableWidgetItem('-'.join(list_keadaan)))

				self.tabel_pesan.setItem(idx, 3, QtWidgets.QTableWidgetItem(str(row[3])))
				self.tabel_pesan.setItem(idx, 4, QtWidgets.QTableWidgetItem(row[4]))
				self.tabel_pesan.setItem(idx, 5, QtWidgets.QTableWidgetItem(str(row[6]) + "/" + str(row[5])))
				idx = idx + 1
		else: 
			print(res[1])

	def showAlert(self,err):
		# Menampilkan pesan kesalahan
		msg = QtWidgets.QMessageBox()
		msg.setIcon(QtWidgets.QMessageBox.Critical)
		msg.setText(err)
		x = msg.exec_()

	def acceptPesanan(self):
		try:
			self.ID_Pesanan = int(self.tabel_pesan.selectedItems()[0].text())
			respon = ubah_status(self.db,self.cursor,self.DB_NAME,self.ID_Pesanan,1)
			print(respon)
			self.loadTable()
		except:
			self.showAlert("Belum memilih pesanan")

	def rejectPesanan(self):
		try:
			self.ID_Pesanan = int(self.tabel_pesan.selectedItems()[0].text())
			respon = ubah_status(self.db,self.cursor,self.DB_NAME,self.ID_Pesanan,-1)
			print(respon)
			self.loadTable()
		except:
			self.showAlert("Belum memilih pesanan")

	def logout(self):
		# Melakukan logout
		from ui_login import Ui_LoginWindow
		self.window = QtWidgets.QMainWindow()
		self.ui = Ui_LoginWindow()
		self.ui.setupUi(self.window)
		self.window.show()
		self.AdminPesananWindow.close()
		print("Logout")
		return

	def to_update_laporan(self):
		# Navigate to update laporan page
		from Admin_UpdateLaporan import Ui_UpdateLaporanWindow
		self.window = QtWidgets.QMainWindow()
		self.ui = Ui_UpdateLaporanWindow()
		self.ui.setupUi(self.window, self.ID_Pengguna)
		self.window.show()
		self.AdminPesananWindow.close()
		print("Update Laporan")
		return
	
	def to_Admin_Home(self):
		# Navigate to update laporan page
		from Admin_Home import Ui_AdminHomeWindow
		self.window = QtWidgets.QMainWindow()
		self.ui = Ui_AdminHomeWindow()
		self.ui.setupUi(self.window, self.ID_Pengguna)
		self.window.show()
		self.AdminPesananWindow.close()
		print("Admin_Home ")
		return

	def to_Data_RS(self):
		# Navigate to update laporan page
		from Admin_RS import Ui_DataRSWindow
		self.window = QtWidgets.QMainWindow()
		self.ui = Ui_DataRSWindow()
		self.ui.setupUi(self.window, self.ID_Pengguna)
		self.window.show()
		self.AdminPesananWindow.close()
		print("Data RS ")
		return

	def retranslateUi(self, AdminPesananWindow):
		_translate = QtCore.QCoreApplication.translate
		AdminPesananWindow.setWindowTitle(_translate("AdminPesananWindow", "AdminPesananWindow"))
		item = self.tabel_pesan.horizontalHeaderItem(0)
		item.setText(_translate("AdminPesananWindow", "ID"))
		item = self.tabel_pesan.horizontalHeaderItem(1)
		item.setText(_translate("AdminPesananWindow", "Pemesan"))
		item = self.tabel_pesan.horizontalHeaderItem(2)
		item.setText(_translate("AdminPesananWindow", "Riwayat"))
		item = self.tabel_pesan.horizontalHeaderItem(3)
		item.setText(_translate("AdminPesananWindow", "Tanggal_Pesan"))
		item = self.tabel_pesan.horizontalHeaderItem(4)
		item.setText(_translate("AdminPesananWindow", "RS"))
		item = self.tabel_pesan.horizontalHeaderItem(5)
		item.setText(_translate("AdminPesananWindow", "Kapasitas"))
		self.header_pesan_2.setText(_translate("AdminPesananWindow", "Daftar Pesanan"))
		username_Pengguna = get_username(self.cursor,self.DB_NAME,self.ID_Pengguna)[1]
		self.Nama_Admin.setText(_translate("PesanRSWindow", "Welcome  "+username_Pengguna))
		self.Accept_Button.setText(_translate("AdminPesananWindow", "Accept"))
		self.Reject_Button.setText(_translate("AdminPesananWindow", "Reject"))
		self.Laporan_Harian.setText(_translate("AdminPesananWindow", "Laporan Harian"))
		self.label.setText(_translate("AdminPesananWindow", "CoverMe"))
		self.RumahSakit.setText(_translate("AdminPesananWindow", "Rumah Sakit"))
		self.Daftar_Pesanan.setText(_translate("AdminPesananWindow", "Daftar Pesanan"))
		self.Home.setText(_translate("AdminPesananWindow", "Home"))
		self.Logout.setText(_translate("AdminPesananWindow", "Logout"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminPesananWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminPesananWindow()
    ui.setupUi(AdminPesananWindow)
    AdminPesananWindow.show()
    sys.exit(app.exec_())
