from PyQt5 import QtCore, QtGui, QtWidgets
from update_laporan import *
from autentikasi import *
from Init_DBData import *
from datetime import date

class Ui_HomeAdminWindow(object):
    def setupUi(self, HomeAdminWindow, ID_Pengguna=1):
        self.HomeAdminWindow = HomeAdminWindow
        self.ID_Pengguna=ID_Pengguna
        self.HomeAdminWindow.setObjectName("HomeAdminWindow")
        self.HomeAdminWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(HomeAdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.background.setText("")
        self.background.setTextFormat(QtCore.Qt.PlainText)
        self.background.setPixmap(QtGui.QPixmap("../img/background.png"))
        self.background.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.background.setObjectName("background")
        self.topbar = QtWidgets.QLabel(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(210, 0, 691, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.topbar.setFont(font)
        self.topbar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(80, 80, 80);")
        self.topbar.setObjectName("topbar")
        self.icon_notif = QtWidgets.QLabel(self.centralwidget)
        self.icon_notif.setGeometry(QtCore.QRect(850, 15, 20, 20))
        self.icon_notif.setText("")
        self.icon_notif.setPixmap(QtGui.QPixmap("../img/notif.png"))
        self.icon_notif.setScaledContents(True)
        self.icon_notif.setObjectName("icon_notif")
        self.icon_calendar = QtWidgets.QLabel(self.centralwidget)
        self.icon_calendar.setGeometry(QtCore.QRect(710, 15, 20, 20))
        self.icon_calendar.setText("")
        self.icon_calendar.setPixmap(QtGui.QPixmap("../img/cal.png"))
        self.icon_calendar.setScaledContents(True)
        self.icon_calendar.setObjectName("icon_calendar")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(740, 15, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.button_home = QtWidgets.QPushButton(self.centralwidget)
        self.button_home.setGeometry(QtCore.QRect(0, 195, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_home.setFont(font)
        self.button_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_home.setAutoFillBackground(False)
        self.button_home.setStyleSheet("background-color: rgb(218, 114, 60);\n"
"color: rgb(255, 255, 255);\n"
"Text-align:left;")
        self.button_home.setFlat(False)
        self.button_home.setObjectName("button_home")
        self.icon_home = QtWidgets.QLabel(self.centralwidget)
        self.icon_home.setGeometry(QtCore.QRect(20, 200, 20, 20))
        self.icon_home.setText("")
        self.icon_home.setPixmap(QtGui.QPixmap("../img/home-white.png"))
        self.icon_home.setScaledContents(True)
        self.icon_home.setObjectName("icon_home")
        self.button_laporan = QtWidgets.QPushButton(self.centralwidget)
        self.button_laporan.setGeometry(QtCore.QRect(0, 226, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_laporan.setFont(font)
        self.button_laporan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_laporan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_laporan.setAutoFillBackground(False)
        self.button_laporan.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_laporan.setFlat(True)
        self.button_laporan.setObjectName("button_laporan")
        self.icon_laporan = QtWidgets.QLabel(self.centralwidget)
        self.icon_laporan.setGeometry(QtCore.QRect(20, 233, 20, 20))
        self.icon_laporan.setText("")
        self.icon_laporan.setPixmap(QtGui.QPixmap("../img/laporan-gray.png"))
        self.icon_laporan.setScaledContents(True)
        self.icon_laporan.setObjectName("icon_laporan")
        self.icon_rs = QtWidgets.QLabel(self.centralwidget)
        self.icon_rs.setGeometry(QtCore.QRect(20, 263, 20, 20))
        self.icon_rs.setText("")
        self.icon_rs.setPixmap(QtGui.QPixmap("../img/hospital-gray.png"))
        self.icon_rs.setScaledContents(True)
        self.icon_rs.setObjectName("icon_rs")
        self.button_rs = QtWidgets.QPushButton(self.centralwidget)
        self.button_rs.setGeometry(QtCore.QRect(0, 257, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_rs.setFont(font)
        self.button_rs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_rs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_rs.setAutoFillBackground(False)
        self.button_rs.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_rs.setFlat(True)
        self.button_rs.setObjectName("button_rs")
        self.icon_pesanan = QtWidgets.QLabel(self.centralwidget)
        self.icon_pesanan.setGeometry(QtCore.QRect(20, 294, 20, 20))
        self.icon_pesanan.setText("")
        self.icon_pesanan.setPixmap(QtGui.QPixmap("../img/pesanan-gray.png"))
        self.icon_pesanan.setScaledContents(True)
        self.icon_pesanan.setObjectName("icon_pesanan")
        self.button_pesanan = QtWidgets.QPushButton(self.centralwidget)
        self.button_pesanan.setGeometry(QtCore.QRect(0, 288, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_pesanan.setFont(font)
        self.button_pesanan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_pesanan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_pesanan.setAutoFillBackground(False)
        self.button_pesanan.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_pesanan.setFlat(True)
        self.button_pesanan.setObjectName("button_pesanan")
        self.button_logout = QtWidgets.QPushButton(self.centralwidget)
        self.button_logout.setGeometry(QtCore.QRect(0, 534, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_logout.setFont(font)
        self.button_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_logout.setAutoFillBackground(False)
        self.button_logout.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_logout.setFlat(True)
        self.button_logout.setObjectName("button_logout")
        self.icon_logout = QtWidgets.QLabel(self.centralwidget)
        self.icon_logout.setGeometry(QtCore.QRect(20, 540, 20, 20))
        self.icon_logout.setText("")
        self.icon_logout.setPixmap(QtGui.QPixmap("../img/power-gray.png"))
        self.icon_logout.setScaledContents(True)
        self.icon_logout.setObjectName("icon_logout")
        self.icon_avatar = QtWidgets.QLabel(self.centralwidget)
        self.icon_avatar.setGeometry(QtCore.QRect(0, 140, 61, 41))
        self.icon_avatar.setText("")
        self.icon_avatar.setPixmap(QtGui.QPixmap("../img/avatar.png"))
        self.icon_avatar.setScaledContents(True)
        self.icon_avatar.setObjectName("icon_avatar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 146, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(150, 150, 150);")
        self.label.setObjectName("label")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(60, 161, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("color: rgb(150, 150, 150);")
        self.label_email.setObjectName("label_email")
        self.picture_graph = QtWidgets.QLabel(self.centralwidget)
        self.picture_graph.setGeometry(QtCore.QRect(280, 60, 571, 311))
        self.picture_graph.setText("")
        self.picture_graph.setPixmap(QtGui.QPixmap("../img/graph.png"))
        self.picture_graph.setScaledContents(True)
        self.picture_graph.setObjectName("picture_graph")
        self.box_positif = QtWidgets.QLabel(self.centralwidget)
        self.box_positif.setGeometry(QtCore.QRect(455, 380, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.box_positif.setFont(font)
        self.box_positif.setStyleSheet("border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(218, 114, 60);")
        self.box_positif.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.box_positif.setObjectName("box_positif")
        self.label_positif = QtWidgets.QLabel(self.centralwidget)
        self.label_positif.setGeometry(QtCore.QRect(515, 415, 144, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_positif.setFont(font)
        self.label_positif.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_positif.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_positif.setObjectName("label_positif")
        self.icon_positif = QtWidgets.QLabel(self.centralwidget)
        self.icon_positif.setGeometry(QtCore.QRect(465, 413, 40, 40))
        self.icon_positif.setText("")
        self.icon_positif.setPixmap(QtGui.QPixmap("../img/plus-white.png"))
        self.icon_positif.setScaledContents(True)
        self.icon_positif.setObjectName("icon_positif")
        self.box_sembuh = QtWidgets.QLabel(self.centralwidget)
        self.box_sembuh.setGeometry(QtCore.QRect(250, 485, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.box_sembuh.setFont(font)
        self.box_sembuh.setStyleSheet("border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(218, 114, 60);")
        self.box_sembuh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.box_sembuh.setObjectName("box_sembuh")
        self.icon_sembuh = QtWidgets.QLabel(self.centralwidget)
        self.icon_sembuh.setGeometry(QtCore.QRect(260, 517, 40, 40))
        self.icon_sembuh.setText("")
        self.icon_sembuh.setPixmap(QtGui.QPixmap("../img/healthy-white.png"))
        self.icon_sembuh.setScaledContents(True)
        self.icon_sembuh.setObjectName("icon_sembuh")
        self.label_sembuh = QtWidgets.QLabel(self.centralwidget)
        self.label_sembuh.setGeometry(QtCore.QRect(310, 520, 144, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_sembuh.setFont(font)
        self.label_sembuh.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_sembuh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sembuh.setObjectName("label_sembuh")
        self.box_meninggal = QtWidgets.QLabel(self.centralwidget)
        self.box_meninggal.setGeometry(QtCore.QRect(660, 485, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.box_meninggal.setFont(font)
        self.box_meninggal.setStyleSheet("border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(218, 114, 60);")
        self.box_meninggal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.box_meninggal.setObjectName("box_meninggal")
        self.icon_meninggal = QtWidgets.QLabel(self.centralwidget)
        self.icon_meninggal.setGeometry(QtCore.QRect(670, 517, 41, 41))
        self.icon_meninggal.setText("")
        self.icon_meninggal.setPixmap(QtGui.QPixmap("../img/dead-white.png"))
        self.icon_meninggal.setScaledContents(True)
        self.icon_meninggal.setObjectName("icon_meninggal")
        self.label_meninggal = QtWidgets.QLabel(self.centralwidget)
        self.label_meninggal.setGeometry(QtCore.QRect(720, 520, 144, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_meninggal.setFont(font)
        self.label_meninggal.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_meninggal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_meninggal.setObjectName("label_meninggal")
        self.background.raise_()
        self.topbar.raise_()
        self.icon_notif.raise_()
        self.icon_calendar.raise_()
        self.label_date.raise_()
        self.button_home.raise_()
        self.icon_home.raise_()
        self.button_laporan.raise_()
        self.icon_laporan.raise_()
        self.button_rs.raise_()
        self.icon_rs.raise_()
        self.button_pesanan.raise_()
        self.icon_pesanan.raise_()
        self.button_logout.raise_()
        self.icon_logout.raise_()
        self.icon_avatar.raise_()
        self.label.raise_()
        self.label_email.raise_()
        self.picture_graph.raise_()
        self.box_positif.raise_()
        self.label_positif.raise_()
        self.icon_positif.raise_()
        self.box_sembuh.raise_()
        self.icon_sembuh.raise_()
        self.label_sembuh.raise_()
        self.box_meninggal.raise_()
        self.icon_meninggal.raise_()
        self.label_meninggal.raise_()
        self.HomeAdminWindow.setCentralWidget(self.centralwidget)

        # Melakukan setup SQL
        self.setupSql()

        self.retranslateUi(HomeAdminWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeAdminWindow)
        
        # Mendapatkan semua data
        self.refreshAllValue()
        
        # Connect button navigator
        self.button_laporan.clicked.connect(self.to_update_laporan)
        self.button_logout.clicked.connect(self.logout)
        self.button_rs.clicked.connect(self.to_Data_RS)
        self.button_pesanan.clicked.connect(self.to_Admin_Pesanan)


    def retranslateUi(self, HomeAdminWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeAdminWindow.setWindowTitle(_translate("HomeAdminWindow", "HomeAdminWindow"))
        self.topbar.setText(_translate("HomeAdminWindow", "     Home"))
        today = date.today()
        d2 = today.strftime("%d %B %Y")
        self.label_date.setText(_translate("HomeAdminWindow", d2))
        self.button_home.setText(_translate("HomeAdminWindow", "              Home"))
        self.button_laporan.setText(_translate("HomeAdminWindow", "              Laporan Harian"))
        self.button_rs.setText(_translate("HomeAdminWindow", "              Rumah Sakit"))
        self.button_pesanan.setText(_translate("HomeAdminWindow", "              Daftar Pesanan"))
        self.button_logout.setText(_translate("HomeAdminWindow", "              Logout"))
        Nama_User = get_nama(self.cursor,self.DB_NAME,self.ID_Pengguna)
        self.label.setText(_translate("HomeAdminWindow", Nama_User[1]))
        Email_User = get_email(self.cursor,self.DB_NAME,self.ID_Pengguna)
        self.label_email.setText(_translate("HomeAdminWindow", Email_User[1]))
        self.box_positif.setText(_translate("HomeAdminWindow", "Kasus Positif    "))
        self.label_positif.setText(_translate("HomeAdminWindow", "100000"))
        self.box_sembuh.setText(_translate("HomeAdminWindow", "Pasien Sembuh   "))
        self.label_sembuh.setText(_translate("HomeAdminWindow", "100000"))
        self.box_meninggal.setText(_translate("HomeAdminWindow", "Pasien Meninggal    "))
        self.label_meninggal.setText(_translate("HomeAdminWindow", "100000"))

    def setupSql(self):
    # Melakukan setup koneksi SQL
        # Configurasi
        # Nama database
        self.DB_NAME = get_DB_NAME()
        # Database yang sedang connect
        self.db = mysql.connector.connect(**get_config())
        # Cursor database
        self.cursor = self.db.cursor()

    def refreshAllValue(self):
        self.label_positif.setText(str(get_kasus_positif(self.cursor, self.DB_NAME)[1][0][0]))
        self.label_sembuh.setText(str(get_pasien_sembuh(self.cursor, self.DB_NAME)[1][0][0]))
        self.label_meninggal.setText(str(get_pasien_meninggal(self.cursor, self.DB_NAME)[1][0][0]))

    def logout(self):
        # Melakukan logout
        from Login_User import Ui_LoginScreen
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LoginScreen()
        self.ui.setupUi(self.window)
        self.window.show()
        self.HomeAdminWindow.close()
        print("Logout")
        return
        
    def to_Data_RS(self):
        # Navigate to update laporan page
        from RS_Admin import UI_RSAdminWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = UI_RSAdminWindow()
        self.ui.setupUi(self.window, self.ID_Pengguna)
        self.window.show()
        self.HomeAdminWindow.close()
        print("Data RS ")
        return

    def to_update_laporan(self):
        # Navigate to update laporan page
        from Laporan_Admin import Ui_LaporanAdminWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LaporanAdminWindow()
        self.ui.setupUi(self.window, self.ID_Pengguna)
        self.window.show()
        self.HomeAdminWindow.close()
        print("Update Laporan")
        return

    def to_Admin_Pesanan(self):
        # Navigate to update laporan page
        from Pesanan_Admin import Ui_PesananAdminWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PesananAdminWindow()
        self.ui.setupUi(self.window, self.ID_Pengguna)
        self.window.show()
        self.HomeAdminWindow.close()
        print("Admin_Pesanan ")
        return

if __name__ == "__main__":
    import sys
    InitDB()
    app = QtWidgets.QApplication(sys.argv)
    HomeAdminWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeAdminWindow()
    ui.setupUi(HomeAdminWindow)
    HomeAdminWindow.show()
    sys.exit(app.exec_())
