# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Klien_PesanRS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pesanan import *
from rumah_sakit import *
import mysql.connector


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(900, 591)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.Sidebar = QtWidgets.QFrame(self.centralwidget)
		self.Sidebar.setGeometry(QtCore.QRect(0, 0, 211, 591))
		self.Sidebar.setStyleSheet("QFrame{\n"
		"    background-color: rgb(72, 67, 67);\n"
		"}")
		self.Sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.Sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
		self.Sidebar.setObjectName("Sidebar")
		self.SuhuHarian = QtWidgets.QPushButton(self.Sidebar)
		self.SuhuHarian.setGeometry(QtCore.QRect(20, 180, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.SuhuHarian.setFont(font)
		self.SuhuHarian.setStyleSheet("QPushButton{\n"
		"    background-color: rgb(72, 67, 67);\n"
		"    color: rgb(255, 255, 255);\n"
		"}")
		self.SuhuHarian.setObjectName("SuhuHarian")
		self.label = QtWidgets.QLabel(self.Sidebar)
		self.label.setGeometry(QtCore.QRect(20, 20, 171, 71))
		font = QtGui.QFont()
		font.setPointSize(28)
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setStyleSheet("QLabel{\n"
		"    color: rgb(255, 255, 255);\n"
		"}")
		self.label.setObjectName("label")
		self.PesanRS = QtWidgets.QPushButton(self.Sidebar)
		self.PesanRS.setGeometry(QtCore.QRect(20, 250, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.PesanRS.setFont(font)
		self.PesanRS.setStyleSheet("QPushButton{\n"
		"    background-color: rgb(72, 67, 67);\n"
		"    color: rgb(255, 255, 255);\n"
		"}")
		self.PesanRS.setObjectName("PesanRS")
		self.Pesanan = QtWidgets.QPushButton(self.Sidebar)
		self.Pesanan.setGeometry(QtCore.QRect(20, 320, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Pesanan.setFont(font)
		self.Pesanan.setStyleSheet("QPushButton{\n"
		"    background-color: rgb(72, 67, 67);\n"
		"    color: rgb(255, 255, 255);\n"
		"}")
		self.Pesanan.setObjectName("Pesanan")
		self.Home = QtWidgets.QPushButton(self.Sidebar)
		self.Home.setGeometry(QtCore.QRect(20, 110, 171, 51))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Home.setFont(font)
		self.Home.setStyleSheet("QPushButton{\n"
		"    background-color: rgb(72, 67, 67);\n"
		"    color: rgb(255, 255, 255);\n"
		"}")
		self.Home.setObjectName("Home")
		self.Nama_Klien = QtWidgets.QLabel(self.centralwidget)
		self.Nama_Klien.setGeometry(QtCore.QRect(640, 10, 251, 61))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(16)
		self.Nama_Klien.setFont(font)
		self.Nama_Klien.setObjectName("Nama_Klien")
		self.header_pesan = QtWidgets.QLabel(self.centralwidget)
		self.header_pesan.setGeometry(QtCore.QRect(250, 60, 301, 41))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.header_pesan.setFont(font)
		self.header_pesan.setStyleSheet("QLabel{\n"
		"    color: rgb(0, 0, 0);\n"
		"}")
		self.header_pesan.setObjectName("header_pesan")
		self.tabel_pesan = QtWidgets.QTableWidget(self.centralwidget)
		self.tabel_pesan.setGeometry(QtCore.QRect(250, 110, 588, 361))
		self.tabel_pesan.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
		self.tabel_pesan.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.tabel_pesan.setColumnCount(4)
		self.tabel_pesan.setObjectName("tabel_pesan")
		self.tabel_pesan.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tabel_pesan.setHorizontalHeaderItem(3, item)
		self.tabel_pesan.verticalHeader().setVisible(False)
		self.tabel_pesan.verticalHeader().setDefaultSectionSize(30)
		self.button_pesan = QtWidgets.QPushButton(self.centralwidget)
		self.button_pesan.setGeometry(QtCore.QRect(630, 500, 211, 31))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.button_pesan.setFont(font)
		self.button_pesan.setStyleSheet("QPushButton{\n"
		"    background-color: rgb(92, 184, 92);\n"
		"}")
		self.button_pesan.setObjectName("button_pesan")
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		# ===================================================
		self.ID_Pengguna = 5 #Sementara
		config = {
			'user': 'root',
			'password': '',
			'host': 'localhost'
		}
		self.DB_NAME = 'Cover_Me'
		self.db = mysql.connector.connect(**config)
		self.cursor = self.db.cursor()
		self.tabel_pesan.setColumnWidth(0,225)
		self.tabel_pesan.setColumnWidth(1,150)
		self.tabel_pesan.setColumnWidth(2,105)
		self.tabel_pesan.setColumnWidth(3,105)
		self.button_pesan.clicked.connect(self.showConfirmBox)
		self.loadTable()
		# ===================================================
	# =======================================================
	def pesanRS(self, i):
		if (i.text()=="&Yes"):
			Nama_RS = str(self.tabel_pesan.selectedItems()[0].text())
			ID_RS = get_idRS(self.db,self.cursor,self.DB_NAME,Nama_RS)[1]
			res= add_new_pesanan(self.db,self.cursor,self.DB_NAME,ID_RS,self.ID_Pengguna)
			if (res[0]==1):
				tambah_pasien(self.db,self.cursor,self.DB_NAME,Nama_RS)
				self.loadTable()
			else:
				self.showAlert(res[1])
		else :
			print("Gjadi Pesen")

	def showAlert(self,err):
		msg = QtWidgets.QMessageBox()
		msg.setIcon(QtWidgets.QMessageBox.Critical)
		msg.setText(err)
		x = msg.exec_()

	def showConfirmBox(self):
		try:
			print(self.tabel_pesan.selectedItems()[0].text())
			msg = QtWidgets.QMessageBox()
			msg.setWindowTitle("Konfirmasi Pemesanan")
			msg.setText("Apakah anda yakin ingin memesan :")
			msg.setInformativeText("Nama: "+self.tabel_pesan.selectedItems()[0].text() +"\nHarga :"+self.tabel_pesan.selectedItems()[1].text())
			msg.setIcon(QtWidgets.QMessageBox.Question)
			msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
			msg.setDefaultButton(QtWidgets.QMessageBox.Yes)
			msg.buttonClicked.connect(self.pesanRS)
			x = msg.exec_()
		except:
			self.showAlert("Anda belum memilih rumah sakit")

	def loadTable(self):
		res = get_rs_klien(self.cursor,self.DB_NAME)
		if (res[0]==1):
			data = res[1]
			self.tabel_pesan.setRowCount(len(data))
			idx = 0
			for row in data:
				print(row)
				self.tabel_pesan.setItem(idx, 0, QtWidgets.QTableWidgetItem(row[0]))
				self.tabel_pesan.setItem(idx, 1, QtWidgets.QTableWidgetItem(str(row[1])))
				self.tabel_pesan.setItem(idx, 2, QtWidgets.QTableWidgetItem(str(row[2])))
				self.tabel_pesan.setItem(idx, 3, QtWidgets.QTableWidgetItem(str(row[3])))
				idx = idx + 1
		else: 
			self.showAlert(res[1])
	# =======================================================
	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.SuhuHarian.setText(_translate("MainWindow", "Suhu Harian"))
		self.label.setText(_translate("MainWindow", "CoverMe"))
		self.PesanRS.setText(_translate("MainWindow", "Pesan RS"))
		self.Pesanan.setText(_translate("MainWindow", "Pesanan"))
		self.Home.setText(_translate("MainWindow", "Home"))
		self.Nama_Klien.setText(_translate("MainWindow", "Welcome  <KlienName>"))
		self.header_pesan.setText(_translate("MainWindow", "Rumah Sakit Tersedia"))
		item = self.tabel_pesan.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Nama_Rs"))
		item = self.tabel_pesan.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "Harga Rumah Sakit"))
		item = self.tabel_pesan.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "Kapasitas"))
		item = self.tabel_pesan.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "Jumlah Pasien"))
		self.button_pesan.setText(_translate("MainWindow", "+ Pesan Rumah Sakit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
