# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_User.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
import re
from PyQt5 import QtCore, QtGui, QtWidgets
from autentikasi import *
from Init_DBData import *

class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        self.LoginScreen = LoginScreen
        self.LoginScreen.setObjectName("LoginScreen")
        self.LoginScreen.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/background-1.png"))
        self.label.setObjectName("label")
        self.login_message = QtWidgets.QLabel(self.centralwidget)
        self.login_message.setGeometry(QtCore.QRect(510, 130, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login_message.setFont(font)
        self.login_message.setStyleSheet("color: rgb(251, 242, 215);\n"
"background-color: rgb(144, 15, 32);")
        self.login_message.setAlignment(QtCore.Qt.AlignCenter)
        self.login_message.setObjectName("login_message")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 90, 356, 486))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_login = QtWidgets.QLabel(self.page)
        self.label_login.setGeometry(QtCore.QRect(120, 30, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color: rgb(144, 15, 32);")
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.label_username = QtWidgets.QLabel(self.page)
        self.label_username.setGeometry(QtCore.QRect(25, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("color: rgb(144, 15, 32);")
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.page)
        self.label_password.setGeometry(QtCore.QRect(25, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color: rgb(144, 15, 32);")
        self.label_password.setObjectName("label_password")
        self.box_username = QtWidgets.QLineEdit(self.page)
        self.box_username.setGeometry(QtCore.QRect(120, 110, 181, 31))
        self.box_username.setObjectName("box_username")
        self.box_password = QtWidgets.QLineEdit(self.page)
        self.box_password.setGeometry(QtCore.QRect(120, 150, 181, 31))
        self.box_password.setStyleSheet("lineedit-password-character: 9679")
        self.box_password.setObjectName("box_password")
        self.login_Button = QtWidgets.QPushButton(self.page)
        self.login_Button.setGeometry(QtCore.QRect(25, 195, 276, 28))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_Button.setFont(font)
        self.login_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_Button.setStyleSheet("background-color: rgb(144, 15, 32);\n"
"color: rgb(251, 242, 215);")
        self.login_Button.setObjectName("login_Button")
        self.label_1 = QtWidgets.QLabel(self.page)
        self.label_1.setGeometry(QtCore.QRect(50, 245, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.frame_login = QtWidgets.QLabel(self.page)
        self.frame_login.setGeometry(QtCore.QRect(0, 0, 356, 376))
        self.frame_login.setStyleSheet("background-color: rgb(251, 242, 215);")
        self.frame_login.setText("")
        self.frame_login.setObjectName("frame_login")
        self.button_toRegister = QtWidgets.QPushButton(self.page)
        self.button_toRegister.setGeometry(QtCore.QRect(186, 242, 71, 26))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_toRegister.setFont(font)
        self.button_toRegister.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_toRegister.setStyleSheet("color: rgb(144, 15, 32);")
        self.button_toRegister.setFlat(True)
        self.button_toRegister.setObjectName("button_toRegister")
        self.frame_login.raise_()
        self.label_login.raise_()
        self.label_username.raise_()
        self.label_password.raise_()
        self.box_password.raise_()
        self.box_username.raise_()
        self.login_Button.raise_()
        self.label_1.raise_()
        self.button_toRegister.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setAutoFillBackground(False)
        self.page_2.setObjectName("page_2")
        self.label_login_2 = QtWidgets.QLabel(self.page_2)
        self.label_login_2.setGeometry(QtCore.QRect(120, 25, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.label_login_2.setFont(font)
        self.label_login_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_2.setObjectName("label_login_2")
        self.frame_login_2 = QtWidgets.QLabel(self.page_2)
        self.frame_login_2.setGeometry(QtCore.QRect(0, 0, 356, 486))
        self.frame_login_2.setStyleSheet("background-color: rgb(251, 242, 215);\n"
"color: rgb(144, 15, 32);")
        self.frame_login_2.setText("")
        self.frame_login_2.setObjectName("frame_login_2")
        self.label_login_3 = QtWidgets.QLabel(self.page_2)
        self.label_login_3.setGeometry(QtCore.QRect(120, 30, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_login_3.setFont(font)
        self.label_login_3.setStyleSheet("color: rgb(144, 15, 32);")
        self.label_login_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_3.setObjectName("label_login_3")
        self.label_password_2 = QtWidgets.QLabel(self.page_2)
        self.label_password_2.setGeometry(QtCore.QRect(25, 165, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_password_2.setFont(font)
        self.label_password_2.setStyleSheet("color: rgb(137, 14, 30);")
        self.label_password_2.setObjectName("label_password_2")
        self.box_telepon = QtWidgets.QLineEdit(self.page_2)
        self.box_telepon.setGeometry(QtCore.QRect(140, 285, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.box_telepon.setFont(font)
        self.box_telepon.setObjectName("box_telepon")
        self.box_alamat = QtWidgets.QLineEdit(self.page_2)
        self.box_alamat.setGeometry(QtCore.QRect(140, 205, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.box_alamat.setFont(font)
        self.box_alamat.setObjectName("box_alamat")
        self.label_email = QtWidgets.QLabel(self.page_2)
        self.label_email.setGeometry(QtCore.QRect(25, 325, 106, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("color: rgb(137, 14, 30);")
        self.label_email.setObjectName("label_email")
        self.box_password_2 = QtWidgets.QLineEdit(self.page_2)
        self.box_password_2.setGeometry(QtCore.QRect(140, 165, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.box_password_2.setFont(font)
        self.box_password_2.setObjectName("box_password_2")
        self.label_alamat = QtWidgets.QLabel(self.page_2)
        self.label_alamat.setGeometry(QtCore.QRect(25, 205, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_alamat.setFont(font)
        self.label_alamat.setStyleSheet("color: rgb(137, 14, 30);")
        self.label_alamat.setObjectName("label_alamat")
        self.label_username_2 = QtWidgets.QLabel(self.page_2)
        self.label_username_2.setGeometry(QtCore.QRect(25, 125, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_username_2.setFont(font)
        self.label_username_2.setStyleSheet("color: rgb(137, 14, 30);")
        self.label_username_2.setObjectName("label_username_2")
        self.dateEdit = QtWidgets.QDateEdit(self.page_2)
        self.dateEdit.setGeometry(QtCore.QRect(140, 245, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(76, 420, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button_register = QtWidgets.QPushButton(self.page_2)
        self.button_register.setGeometry(QtCore.QRect(20, 370, 311, 28))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_register.setFont(font)
        self.button_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_register.setStyleSheet("background-color: rgb(144, 15, 32);\n"
"color: rgb(251, 242, 215);")
        self.button_register.setObjectName("button_register")
        self.box_email = QtWidgets.QLineEdit(self.page_2)
        self.box_email.setGeometry(QtCore.QRect(140, 325, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.box_email.setFont(font)
        self.box_email.setObjectName("box_email")
        self.box_nama = QtWidgets.QLineEdit(self.page_2)
        self.box_nama.setGeometry(QtCore.QRect(140, 85, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.box_nama.setFont(font)
        self.box_nama.setObjectName("box_nama")
        self.label_nama = QtWidgets.QLabel(self.page_2)
        self.label_nama.setGeometry(QtCore.QRect(25, 85, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_nama.setFont(font)
        self.label_nama.setStyleSheet("color: rgb(144, 15, 32);")
        self.label_nama.setObjectName("label_nama")
        self.label_tanggal_lahir = QtWidgets.QLabel(self.page_2)
        self.label_tanggal_lahir.setGeometry(QtCore.QRect(25, 245, 106, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_tanggal_lahir.setFont(font)
        self.label_tanggal_lahir.setStyleSheet("color: rgb(137, 14, 30);")
        self.label_tanggal_lahir.setObjectName("label_tanggal_lahir")
        self.label_telepon = QtWidgets.QLabel(self.page_2)
        self.label_telepon.setGeometry(QtCore.QRect(25, 285, 106, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_telepon.setFont(font)
        self.label_telepon.setStyleSheet("color: rgb(137, 14, 30);")
        self.label_telepon.setObjectName("label_telepon")
        self.box_username_2 = QtWidgets.QLineEdit(self.page_2)
        self.box_username_2.setGeometry(QtCore.QRect(140, 125, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.box_username_2.setFont(font)
        self.box_username_2.setObjectName("box_username_2")
        self.button_toLogin = QtWidgets.QPushButton(self.page_2)
        self.button_toLogin.setGeometry(QtCore.QRect(210, 417, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_toLogin.setFont(font)
        self.button_toLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_toLogin.setStyleSheet("color: rgb(144, 15, 32);")
        self.button_toLogin.setFlat(True)
        self.button_toLogin.setObjectName("button_toLogin")
        self.stackedWidget.addWidget(self.page_2)
        self.register_message = QtWidgets.QLabel(self.centralwidget)
        self.register_message.setGeometry(QtCore.QRect(510, 130, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.register_message.setFont(font)
        self.register_message.setStyleSheet("color: rgb(251, 242, 215);\n"
"background-color: rgb(144, 15, 32);")
        self.register_message.setAlignment(QtCore.Qt.AlignCenter)
        self.register_message.setObjectName("register_message")
        self.label.raise_()
        self.stackedWidget.raise_()
        self.register_message.raise_()
        self.login_message.raise_()
        self.LoginScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginScreen)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

        self.box_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.box_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        
        # Fungsionalitas Tambahan
        # Setup SQL
        self.setupSQL()
        
        # Ketika tombol toRegister diklik
        self.button_toRegister.clicked.connect(self.toRegister)
        # Ketika tombol toLogin diklik
        self.button_toLogin.clicked.connect(self.toLogin)
        
        # Ketika tombol login diklik
        self.login_Button.clicked.connect(self.login)
        
        # Ketika tombol register diklik
        self.button_register.clicked.connect(self.register)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "LoginScreen"))
        self.login_message.setText(_translate("LoginScreen", "Welcome back"))
        self.label_login.setText(_translate("LoginScreen", "LOGIN"))
        self.label_username.setText(_translate("LoginScreen", "Username"))
        self.label_password.setText(_translate("LoginScreen", "Password"))
        self.login_Button.setText(_translate("LoginScreen", "Login"))
        self.label_1.setText(_translate("LoginScreen", "Belum punya akun?"))
        self.button_toRegister.setText(_translate("LoginScreen", "Register"))
        self.label_login_2.setText(_translate("LoginScreen", "REGISTER"))
        self.label_login_3.setText(_translate("LoginScreen", "REGISTER"))
        self.label_password_2.setText(_translate("LoginScreen", "Password"))
        self.label_email.setText(_translate("LoginScreen", "Email"))
        self.label_alamat.setText(_translate("LoginScreen", "Alamat"))
        self.label_username_2.setText(_translate("LoginScreen", "Username"))
        self.label_3.setText(_translate("LoginScreen", "Sudah punya akun?"))
        self.button_register.setText(_translate("LoginScreen", "Register"))
        self.label_nama.setText(_translate("LoginScreen", "Nama"))
        self.label_tanggal_lahir.setText(_translate("LoginScreen", "Tanggal Lahir"))
        self.label_telepon.setText(_translate("LoginScreen", "Telepon"))
        self.button_toLogin.setText(_translate("LoginScreen", "Login"))
        self.register_message.setText(_translate("LoginScreen", "Welcome to CoverME"))
        
    def showAlert(self,err):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.setWindowTitle("Peringatan")
        msg.setText(err)
        x = msg.exec_()

    def showSucc(self,succ):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setWindowTitle("Berhasil")
        msg.setText(succ)
        x = msg.exec_()
    
    def setupSQL(self):
        # Configurasi
        # Nama database
        self.DB_NAME = get_DB_NAME()
        # Database yang sedang connect
        self.db = mysql.connector.connect(**get_config())
        # Cursor database
        self.cursor = self.db.cursor()
    
    
    def toRegister(self):
        self.stackedWidget.setCurrentIndex(1)
        self.login_message.setVisible(False)
        self.register_message.setVisible(True)

    def toLogin(self):
        self.stackedWidget.setCurrentIndex(0)
        self.login_message.setVisible(True)
        self.register_message.setVisible(False)
    
    def login(self):
        username = self.box_username.text()
        password = self.box_password.text()

        if len(username) == 0 or len(password) == 0:
            self.showAlert("Kolom username atau password tidak boleh kosong")
            return
        
        val = [username, password]
        result = get_user_id(self.cursor,self.DB_NAME, val)
        
        if result[0] == 1:
            # self.showSucc("Login berhasil")
            ID_Pengguna = result[1]
            Role = get_role(self.cursor,self.DB_NAME, ID_Pengguna)[1]
            print(Role)
            if (Role =="Klien"):
                self.toKlienHome(ID_Pengguna)
            else :
                self.to_Admin_Home(ID_Pengguna)
            return
        if result[0] == -1:
            self.showAlert("Password salah")
            return
        if result[0] == -2:
            self.showAlert("Username tidak ditemukan")
            return
        if result[0] == 0:
            print(result[1])
            self.showAlert("General Error")
            return
            
    def register(self):
        nama = self.box_nama.text()
        username = self.box_username_2.text()
        password = self.box_password_2.text()
        alamat = self.box_alamat.text()
        tanggal_lahir = str(self.dateEdit.date().toPyDate())
        telepon = self.box_telepon.text()   
        email = self.box_email.text()
        
        val = [nama, username, password, email, alamat, tanggal_lahir, telepon]
        for data in val:
            if len(data) == 0:
                self.showAlert("Tidak boleh ada kolom yang kosong")
                return
        
        regex_email = "^(\w|\.|\_|\-)+[@](\w|\_|\-|\.)+[.]\w{2,3}$"
        if not re.search(regex_email, email):
            self.showAlert("Format email salah")
            return
        
        result = add_new_user(self.db, self.cursor, self.DB_NAME, val)
        
        if result[0] == 1:
            self.showSucc("Registrasi berhasil, silahkan login")
            self.box_nama.setText("")
            self.box_username_2.setText("")
            self.box_password_2.setText("")
            self.box_alamat.setText("")
            self.box_telepon.setText("")   
            self.box_email.setText("")
            return
        
        if result[0] == -1:
            self.showAlert("Username sudah digunakan")
            return
        
        if result[0] == 0:
            print(result[1])
            self.showAlert("General Error")
            return
        
    def to_Admin_Home(self, ID_Pengguna):
        # Navigate to update laporan page
        from Home_Admin import Ui_HomeAdminWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HomeAdminWindow()
        self.ui.setupUi(self.window, ID_Pengguna)
        self.window.show()
        self.LoginScreen.close()
        print("Home_Admin")
        return
    
    def toKlienHome(self,ID_Pengguna):
        from Home_Klien import Ui_HomeKlienWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HomeKlienWindow()
        self.ui.setupUi(self.window,ID_Pengguna)
        self.window.show()
        self.LoginScreen.close()
        print("Klien_Home")

if __name__ == "__main__":
    import sys
    InitDB()
    app = QtWidgets.QApplication(sys.argv)
    LoginScreen = QtWidgets.QMainWindow()
    ui = Ui_LoginScreen()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
