from PyQt5 import QtCore, QtGui, QtWidgets
from autentikasi import *
from Init_DBData import *
from pesanan import *
from rumah_sakit import *
from datetime import date

class Ui_PesananKlienWindow(object):
    def setupUi(self, PesananKlienWindow, ID_Pengguna=1):
        self.PesananKlienWindow = PesananKlienWindow
        self.ID_Pengguna =ID_Pengguna
        self.PesananKlienWindow.setObjectName("PesananKlienWindow")
        self.PesananKlienWindow.resize(900, 600)
        self.PesananKlienWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(PesananKlienWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.background.setText("")
        self.background.setTextFormat(QtCore.Qt.PlainText)
        self.background.setPixmap(QtGui.QPixmap("../img/background.png"))
        self.background.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.background.setObjectName("background")
        self.topbar = QtWidgets.QLabel(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(210, 0, 691, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.topbar.setFont(font)
        self.topbar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(80, 80, 80);")
        self.topbar.setObjectName("topbar")
        self.icon_notif = QtWidgets.QLabel(self.centralwidget)
        self.icon_notif.setGeometry(QtCore.QRect(850, 15, 20, 20))
        self.icon_notif.setText("")
        self.icon_notif.setPixmap(QtGui.QPixmap("../img/notif.png"))
        self.icon_notif.setScaledContents(True)
        self.icon_notif.setObjectName("icon_notif")
        self.icon_calendar = QtWidgets.QLabel(self.centralwidget)
        self.icon_calendar.setGeometry(QtCore.QRect(710, 15, 20, 20))
        self.icon_calendar.setText("")
        self.icon_calendar.setPixmap(QtGui.QPixmap("../img/cal.png"))
        self.icon_calendar.setScaledContents(True)
        self.icon_calendar.setObjectName("icon_calendar")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(740, 15, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.button_home = QtWidgets.QPushButton(self.centralwidget)
        self.button_home.setGeometry(QtCore.QRect(0, 195, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_home.setFont(font)
        self.button_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_home.setAutoFillBackground(False)
        self.button_home.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_home.setFlat(True)
        self.button_home.setObjectName("button_home")
        self.icon_home = QtWidgets.QLabel(self.centralwidget)
        self.icon_home.setGeometry(QtCore.QRect(20, 200, 20, 20))
        self.icon_home.setText("")
        self.icon_home.setPixmap(QtGui.QPixmap("../img/home-gray.png"))
        self.icon_home.setScaledContents(True)
        self.icon_home.setObjectName("icon_home")
        self.button_suhu = QtWidgets.QPushButton(self.centralwidget)
        self.button_suhu.setGeometry(QtCore.QRect(0, 226, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_suhu.setFont(font)
        self.button_suhu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_suhu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_suhu.setAutoFillBackground(False)
        self.button_suhu.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_suhu.setFlat(True)
        self.button_suhu.setObjectName("button_suhu")
        self.icon_suhu = QtWidgets.QLabel(self.centralwidget)
        self.icon_suhu.setGeometry(QtCore.QRect(20, 233, 20, 20))
        self.icon_suhu.setText("")
        self.icon_suhu.setPixmap(QtGui.QPixmap("../img/termo-gray.png"))
        self.icon_suhu.setScaledContents(True)
        self.icon_suhu.setObjectName("icon_suhu")
        self.icon_pesan = QtWidgets.QLabel(self.centralwidget)
        self.icon_pesan.setGeometry(QtCore.QRect(20, 263, 20, 20))
        self.icon_pesan.setText("")
        self.icon_pesan.setPixmap(QtGui.QPixmap("../img/order-gray.png"))
        self.icon_pesan.setScaledContents(True)
        self.icon_pesan.setObjectName("icon_pesan")
        self.icon_pesanan = QtWidgets.QLabel(self.centralwidget)
        self.icon_pesanan.setGeometry(QtCore.QRect(20, 294, 20, 20))
        self.icon_pesanan.setText("")
        self.icon_pesanan.setPixmap(QtGui.QPixmap("../img/pesanan-white.png"))
        self.icon_pesanan.setScaledContents(True)
        self.icon_pesanan.setObjectName("icon_pesanan")
        self.button_pesanan = QtWidgets.QPushButton(self.centralwidget)
        self.button_pesanan.setGeometry(QtCore.QRect(0, 288, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_pesanan.setFont(font)
        self.button_pesanan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_pesanan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_pesanan.setAutoFillBackground(False)
        self.button_pesanan.setStyleSheet("background-color: rgb(218, 114, 60);\n"
"color: rgb(255, 255, 255);\n"
"Text-align:left;")
        self.button_pesanan.setFlat(False)
        self.button_pesanan.setObjectName("button_pesanan")
        self.button_logout = QtWidgets.QPushButton(self.centralwidget)
        self.button_logout.setGeometry(QtCore.QRect(0, 534, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_logout.setFont(font)
        self.button_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_logout.setAutoFillBackground(False)
        self.button_logout.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_logout.setFlat(True)
        self.button_logout.setObjectName("button_logout")
        self.icon_logout = QtWidgets.QLabel(self.centralwidget)
        self.icon_logout.setGeometry(QtCore.QRect(20, 540, 20, 20))
        self.icon_logout.setText("")
        self.icon_logout.setPixmap(QtGui.QPixmap("../img/power-gray.png"))
        self.icon_logout.setScaledContents(True)
        self.icon_logout.setObjectName("icon_logout")
        self.icon_avatar = QtWidgets.QLabel(self.centralwidget)
        self.icon_avatar.setGeometry(QtCore.QRect(0, 140, 61, 41))
        self.icon_avatar.setText("")
        self.icon_avatar.setPixmap(QtGui.QPixmap("../img/avatar.png"))
        self.icon_avatar.setScaledContents(True)
        self.icon_avatar.setObjectName("icon_avatar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 146, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(150, 150, 150);")
        self.label.setObjectName("label")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(60, 161, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("color: rgb(150, 150, 150);")
        self.label_email.setObjectName("label_email")
        self.img_people = QtWidgets.QLabel(self.centralwidget)
        self.img_people.setGeometry(QtCore.QRect(310, 80, 511, 291))
        self.img_people.setStyleSheet("border-radius:20px;")
        self.img_people.setText("")
        self.img_people.setPixmap(QtGui.QPixmap("../img/people.png"))
        self.img_people.setScaledContents(True)
        self.img_people.setObjectName("img_people")
        self.label_no_rs1 = QtWidgets.QLabel(self.centralwidget)
        self.label_no_rs1.setGeometry(QtCore.QRect(297, 380, 541, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_no_rs1.setFont(font)
        self.label_no_rs1.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_no_rs1.setObjectName("label_no_rs1")
        self.label_no_rs2 = QtWidgets.QLabel(self.centralwidget)
        self.label_no_rs2.setGeometry(QtCore.QRect(390, 410, 321, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_no_rs2.setFont(font)
        self.label_no_rs2.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_no_rs2.setObjectName("label_no_rs2")
        self.label_no_rs3 = QtWidgets.QLabel(self.centralwidget)
        self.label_no_rs3.setGeometry(QtCore.QRect(440, 440, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_no_rs3.setFont(font)
        self.label_no_rs3.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_no_rs3.setObjectName("label_no_rs3")
        self.background_pesanan = QtWidgets.QLabel(self.centralwidget)
        self.background_pesanan.setGeometry(QtCore.QRect(430, 220, 451, 361))
        self.background_pesanan.setStyleSheet("background-color: rgb(251, 242, 215);\n"
"border-radius:15px;\n"
"")
        self.background_pesanan.setText("")
        self.background_pesanan.setObjectName("background_pesanan")
        self.img_rs = QtWidgets.QLabel(self.centralwidget)
        self.img_rs.setGeometry(QtCore.QRect(240, 280, 391, 261))
        self.img_rs.setText("")
        self.img_rs.setPixmap(QtGui.QPixmap("../img/rs.jpg"))
        self.img_rs.setScaledContents(True)
        self.img_rs.setObjectName("img_rs")
        self.button_action_pesanan = QtWidgets.QPushButton(self.centralwidget)
        self.button_action_pesanan.setEnabled(True)
        self.button_action_pesanan.setGeometry(QtCore.QRect(645, 460, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_action_pesanan.setFont(font)
        self.button_action_pesanan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_action_pesanan.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(218, 114, 60);")
        self.button_action_pesanan.setObjectName("button_action_pesanan")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(650, 420, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_status.setObjectName("label_status")
        self.tanggal_pesan = QtWidgets.QLabel(self.centralwidget)
        self.tanggal_pesan.setGeometry(QtCore.QRect(760, 380, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tanggal_pesan.setFont(font)
        self.tanggal_pesan.setStyleSheet("color: rgb(145, 9, 30);")
        self.tanggal_pesan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tanggal_pesan.setObjectName("tanggal_pesan")
        self.harga_2 = QtWidgets.QLabel(self.centralwidget)
        self.harga_2.setGeometry(QtCore.QRect(760, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.harga_2.setFont(font)
        self.harga_2.setStyleSheet("color: rgb(145, 9, 30);")
        self.harga_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.harga_2.setObjectName("harga_2")
        self.nama_rs = QtWidgets.QLabel(self.centralwidget)
        self.nama_rs.setGeometry(QtCore.QRect(630, 340, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nama_rs.setFont(font)
        self.nama_rs.setStyleSheet("color: rgb(145, 9, 30);")
        self.nama_rs.setAlignment(QtCore.Qt.AlignCenter)
        self.nama_rs.setObjectName("nama_rs")
        self.label_tanggal_pesan = QtWidgets.QLabel(self.centralwidget)
        self.label_tanggal_pesan.setGeometry(QtCore.QRect(650, 380, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_tanggal_pesan.setFont(font)
        self.label_tanggal_pesan.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_tanggal_pesan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_tanggal_pesan.setObjectName("label_tanggal_pesan")
        self.label_harga = QtWidgets.QLabel(self.centralwidget)
        self.label_harga.setGeometry(QtCore.QRect(650, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_harga.setFont(font)
        self.label_harga.setStyleSheet("color: rgb(145, 9, 30);")
        self.label_harga.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_harga.setObjectName("label_harga")
        self.status_name = QtWidgets.QLabel(self.centralwidget)
        self.status_name.setGeometry(QtCore.QRect(760, 420, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.status_name.setFont(font)
        self.status_name.setStyleSheet("color: rgb(145, 9, 30);")
        self.status_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.status_name.setObjectName("status_name")
        self.icon_pending1 = QtWidgets.QLabel(self.centralwidget)
        self.icon_pending1.setGeometry(QtCore.QRect(733, 80, 130, 130))
        self.icon_pending1.setText("")
        self.icon_pending1.setPixmap(QtGui.QPixmap("../img/recur-gray.png"))
        self.icon_pending1.setScaledContents(True)
        self.icon_pending1.setObjectName("icon_pending1")
        self.label_pending = QtWidgets.QLabel(self.centralwidget)
        self.label_pending.setGeometry(QtCore.QRect(210, 80, 691, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_pending.setFont(font)
        self.label_pending.setStyleSheet("background-color: rgba(218, 114, 60,20%);\n"
"color: rgb(218, 114, 60);")
        self.label_pending.setObjectName("label_pending")
        self.icon_pending3 = QtWidgets.QLabel(self.centralwidget)
        self.icon_pending3.setGeometry(QtCore.QRect(770, 120, 55, 55))
        self.icon_pending3.setText("")
        self.icon_pending3.setPixmap(QtGui.QPixmap("../img/minus-white.png"))
        self.icon_pending3.setScaledContents(True)
        self.icon_pending3.setObjectName("icon_pending3")
        self.icon_pending2 = QtWidgets.QLabel(self.centralwidget)
        self.icon_pending2.setGeometry(QtCore.QRect(734, 81, 128, 128))
        self.icon_pending2.setStyleSheet("border-radius:64px;\n"
"background-color: rgb(218, 114, 60);")
        self.icon_pending2.setText("")
        self.icon_pending2.setObjectName("icon_pending2")
        self.icon_reject2 = QtWidgets.QLabel(self.centralwidget)
        self.icon_reject2.setGeometry(QtCore.QRect(734, 81, 128, 128))
        self.icon_reject2.setStyleSheet("border-radius:64px;\n"
"background-color: rgb(186, 52, 49);")
        self.icon_reject2.setText("")
        self.icon_reject2.setObjectName("icon_reject2")
        self.label_reject = QtWidgets.QLabel(self.centralwidget)
        self.label_reject.setGeometry(QtCore.QRect(210, 80, 691, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_reject.setFont(font)
        self.label_reject.setStyleSheet("color: rgb(145, 9, 30);\n"
"background-color: rgba(255, 35, 35, 20%);")
        self.label_reject.setObjectName("label_reject")
        self.icon_reject1 = QtWidgets.QLabel(self.centralwidget)
        self.icon_reject1.setGeometry(QtCore.QRect(733, 80, 130, 130))
        self.icon_reject1.setText("")
        self.icon_reject1.setPixmap(QtGui.QPixmap("../img/recur-gray.png"))
        self.icon_reject1.setScaledContents(True)
        self.icon_reject1.setObjectName("icon_reject1")
        self.icon_reject3 = QtWidgets.QLabel(self.centralwidget)
        self.icon_reject3.setGeometry(QtCore.QRect(770, 120, 55, 55))
        self.icon_reject3.setText("")
        self.icon_reject3.setPixmap(QtGui.QPixmap("../img/x-white.png"))
        self.icon_reject3.setScaledContents(True)
        self.icon_reject3.setObjectName("icon_reject3")
        self.icon_accept1 = QtWidgets.QLabel(self.centralwidget)
        self.icon_accept1.setGeometry(QtCore.QRect(733, 80, 130, 130))
        self.icon_accept1.setText("")
        self.icon_accept1.setPixmap(QtGui.QPixmap("../img/recur-gray.png"))
        self.icon_accept1.setScaledContents(True)
        self.icon_accept1.setObjectName("icon_accept1")
        self.label_accept = QtWidgets.QLabel(self.centralwidget)
        self.label_accept.setGeometry(QtCore.QRect(210, 80, 691, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_accept.setFont(font)
        self.label_accept.setStyleSheet("background-color: rgba(0, 170, 0,20%);\n"
"color: rgb(37, 120, 51);")
        self.label_accept.setObjectName("label_accept")
        self.icon_accept2 = QtWidgets.QLabel(self.centralwidget)
        self.icon_accept2.setGeometry(QtCore.QRect(734, 81, 128, 128))
        self.icon_accept2.setStyleSheet("border-radius:64px;\n"
"background-color: rgb(16, 223, 3);")
        self.icon_accept2.setText("")
        self.icon_accept2.setObjectName("icon_accept2")
        self.icon_accept3 = QtWidgets.QLabel(self.centralwidget)
        self.icon_accept3.setGeometry(QtCore.QRect(770, 120, 55, 55))
        self.icon_accept3.setText("")
        self.icon_accept3.setPixmap(QtGui.QPixmap("../img/check-white.png"))
        self.icon_accept3.setScaledContents(True)
        self.icon_accept3.setObjectName("icon_accept3")
        self.button_pesan = QtWidgets.QPushButton(self.centralwidget)
        self.button_pesan.setGeometry(QtCore.QRect(0, 257, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_pesan.setFont(font)
        self.button_pesan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_pesan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_pesan.setAutoFillBackground(False)
        self.button_pesan.setStyleSheet("Text-align:left;\n"
"background-color: rgb(251, 242, 215);\n"
"color: rgb(150, 150, 150);")
        self.button_pesan.setFlat(True)
        self.button_pesan.setObjectName("button_pesan")
        self.background.raise_()
        self.topbar.raise_()
        self.icon_notif.raise_()
        self.icon_calendar.raise_()
        self.label_date.raise_()
        self.button_home.raise_()
        self.icon_home.raise_()
        self.button_suhu.raise_()
        self.icon_suhu.raise_()
        self.button_pesanan.raise_()
        self.icon_pesanan.raise_()
        self.button_logout.raise_()
        self.icon_logout.raise_()
        self.icon_avatar.raise_()
        self.label.raise_()
        self.label_email.raise_()
        self.img_people.raise_()
        self.label_no_rs1.raise_()
        self.label_no_rs2.raise_()
        self.label_no_rs3.raise_()
        self.background_pesanan.raise_()
        self.img_rs.raise_()
        self.button_action_pesanan.raise_()
        self.label_status.raise_()
        self.tanggal_pesan.raise_()
        self.harga_2.raise_()
        self.nama_rs.raise_()
        self.label_tanggal_pesan.raise_()
        self.label_harga.raise_()
        self.status_name.raise_()
        self.label_pending.raise_()
        self.icon_pending2.raise_()
        self.icon_pending1.raise_()
        self.icon_pending3.raise_()
        self.icon_reject2.raise_()
        self.label_reject.raise_()
        self.icon_reject1.raise_()
        self.icon_reject3.raise_()
        self.label_accept.raise_()
        self.icon_accept2.raise_()
        self.icon_accept1.raise_()
        self.icon_accept3.raise_()
        self.button_pesan.raise_()
        self.icon_pesan.raise_()
        self.PesananKlienWindow.setCentralWidget(self.centralwidget)

        # Setup SQL
        self.setupSql()

        # Retranslate UI
        self.retranslateUi(PesananKlienWindow)
        QtCore.QMetaObject.connectSlotsByName(PesananKlienWindow)
        
        # Screen Preparation
        self.hideAccept()
        self.hidePending()
        self.hideReject()
        self.hideNoPesanan()
        self.hidePesanan()
        self.refreshPesanan()

        # Connect button
        self.button_action_pesanan.clicked.connect(self.ubah_status_pesanan)
        
        # Apabila tombol Logout di klik
        self.button_logout.clicked.connect(self.logout)
        
        # Apabila tombol Home di klik
        self.button_home.clicked.connect(self.toKlienHome)
        
        # Apabila tombol Suhu Harian di klik
        self.button_suhu.clicked.connect(self.to_suhu_harian)
        
        #Tombol pesanan diklik
        self.button_pesan.clicked.connect(self.to_pesan_rs)
       

    def retranslateUi(self, PesananKlienWindow):
        _translate = QtCore.QCoreApplication.translate
        PesananKlienWindow.setWindowTitle(_translate("PesananKlienWindow", "PesananKlienWindow"))
        self.topbar.setText(_translate("PesananKlienWindow", "     Pesanan Saat Ini"))
        today = date.today()
        d2 = today.strftime("%d %B %Y")
        self.label_date.setText(_translate("PesananKlienWindow", d2))
        self.button_home.setText(_translate("PesananKlienWindow", "              Home"))
        self.button_suhu.setText(_translate("PesananKlienWindow", "              Suhu Harian"))
        self.button_pesanan.setText(_translate("PesananKlienWindow", "              Pesanan"))
        self.button_logout.setText(_translate("PesananKlienWindow", "              Logout"))
        Nama_User = get_nama(self.cursor,self.DB_NAME,self.ID_Pengguna)
        self.label.setText(_translate("PesananKlienWindow", Nama_User[1]))
        Email_User = get_email(self.cursor,self.DB_NAME,self.ID_Pengguna)
        self.label_email.setText(_translate("PesananKlienWindow", Email_User[1]))
        self.label_no_rs1.setText(_translate("PesananKlienWindow", "Anda Sedang Tidak Memesan Rumah Sakit Manapun"))
        self.label_no_rs2.setText(_translate("PesananKlienWindow", "Segera pesan rumah sakit jika suhu tubuh Anda "))
        self.label_no_rs3.setText(_translate("PesananKlienWindow", "berada dalam rentang bahaya!"))
        self.button_action_pesanan.setText(_translate("PesananKlienWindow", "Selesaikan Pesanan"))
        self.label_status.setText(_translate("PesananKlienWindow", "Status                    :"))
        self.tanggal_pesan.setText(_translate("PesananKlienWindow", "18 April 2001"))
        self.harga_2.setText(_translate("PesananKlienWindow", "Rp 50000"))
        self.nama_rs.setText(_translate("PesananKlienWindow", "RS Borromeus"))
        self.label_tanggal_pesan.setText(_translate("PesananKlienWindow", "Tanggal Pesan :"))
        self.label_harga.setText(_translate("PesananKlienWindow", "Harga                    :"))
        self.status_name.setText(_translate("PesananKlienWindow", "Pending"))
        self.label_pending.setText(_translate("PesananKlienWindow", "            Pesanan Anda segera diproses oleh Admin"))
        self.label_reject.setText(_translate("PesananKlienWindow", "            Pesanan Anda telah ditolak oleh Admin"))
        self.label_accept.setText(_translate("PesananKlienWindow", "            Pesanan Anda telah disetujui oleh Admin"))
        self.button_pesan.setText(_translate("PesananKlienWindow", "              Pesan RS"))

    def setupSql(self):
        # Melakukan setup koneksi SQL
        self.DB_NAME = get_DB_NAME()
        self.db = mysql.connector.connect(**get_config())
        self.cursor = self.db.cursor()

    def hideReject(self):
        self.icon_reject1.setVisible(False)
        self.icon_reject2.setVisible(False)
        self.icon_reject3.setVisible(False)
        self.label_reject.setVisible(False)

    def showReject(self):
        self.icon_reject1.setVisible(True)
        self.icon_reject2.setVisible(True)
        self.icon_reject3.setVisible(True)
        self.label_reject.setVisible(True)
        self.status_name.setText("Rejected")
        self.button_action_pesanan.setText("Akhiri pesanan")
    
    def hideAccept(self):
        self.icon_accept1.setVisible(False)
        self.icon_accept2.setVisible(False)
        self.icon_accept3.setVisible(False)
        self.label_accept.setVisible(False)

    def showAccept(self):
        self.icon_accept1.setVisible(True)
        self.icon_accept2.setVisible(True)
        self.icon_accept3.setVisible(True)
        self.label_accept.setVisible(True)
        self.status_name.setText("Accepted")
        self.button_action_pesanan.setText("Bayar pesanan")

    def hidePending(self):
        self.icon_pending1.setVisible(False)
        self.icon_pending2.setVisible(False)
        self.icon_pending3.setVisible(False)
        self.label_pending.setVisible(False)

    def showPending(self):
        self.icon_pending1.setVisible(True)
        self.icon_pending2.setVisible(True)
        self.icon_pending3.setVisible(True)
        self.label_pending.setVisible(True)
        self.status_name.setText("Pending")
        self.button_action_pesanan.setText("Batalkan pesanan")

    def hideNoPesanan(self):
        self.img_people.setVisible(False)
        self.label_no_rs1.setVisible(False)
        self.label_no_rs2.setVisible(False)
        self.label_no_rs3.setVisible(False)
    
    def showNoPesanan(self):
        self.img_people.setVisible(True)
        self.label_no_rs1.setVisible(True)
        self.label_no_rs2.setVisible(True)
        self.label_no_rs3.setVisible(True)

    def hidePesanan(self):
        self.img_rs.setVisible(False)
        self.background_pesanan.setVisible(False)
        self.label_tanggal_pesan.setVisible(False)
        self.label_harga.setVisible(False)
        self.label_status.setVisible(False)
        self.status_name.setVisible(False)
        self.harga_2.setVisible(False)
        self.tanggal_pesan.setVisible(False)
        self.nama_rs.setVisible(False)
        self.button_action_pesanan.setVisible(False)

    def showPesanan(self):
        self.img_rs.setVisible(True)
        self.background_pesanan.setVisible(True)
        self.label_tanggal_pesan.setVisible(True)
        self.label_harga.setVisible(True)
        self.label_status.setVisible(True)
        self.status_name.setVisible(True)
        self.harga_2.setVisible(True)
        self.tanggal_pesan.setVisible(True)
        self.nama_rs.setVisible(True)
        self.button_action_pesanan.setVisible(True)

    def refreshPesanan(self):
        self.hideAccept()
        self.hidePending()
        self.hideReject()
        result = get_pesanan_ongoing(self.cursor, self.DB_NAME, self.ID_Pengguna)[1]
        if(len(result) > 0):
            self.hideNoPesanan()
            self.showPesanan()
            self.nama_rs.setText(result[0][0])
            self.tanggal_pesan.setText(result[0][2].strftime('%d %B %Y'))
            self.harga_2.setText("Rp "+str(result[0][1]))
            if (result[0][3] == -1):
                self.showReject()
            elif(result[0][3] == 0):
                self.showPending()
            elif(result[0][3] == 1):
                self.showAccept()
        else:
            self.hidePesanan()
            self.showNoPesanan()


    def ubah_status_pesanan(self):
        result = get_pesanan_ongoing(self.cursor, self.DB_NAME, self.ID_Pengguna)[1]
        respon = ubah_status(self.db,self.cursor,self.DB_NAME,result[0][4],-2)
        if (result[0][3] == 1):
            kurangi_pasien(self.db,self.cursor,self.DB_NAME,result[0][0])
        self.refreshPesanan()
        
    def logout(self):
        # Melakukan fungsionalitas logout
        from Login_User import Ui_LoginScreen
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LoginScreen()
        self.ui.setupUi(self.window)
        self.window.show()
        self.PesananKlienWindow.close()
        print("Logout")
        return

    def toKlienHome(self,ID_Pengguna):
        from Home_Klien import Ui_HomeKlienWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HomeKlienWindow()
        self.ui.setupUi(self.window,self.ID_Pengguna)
        self.window.show()
        self.PesananKlienWindow.close()
        print("Klien_Home")

    def to_pesan_rs(self):
        # Navigate to update laporan page
        from PesanRS_Klien import Ui_PesanRSKlienWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PesanRSKlienWindow()
        self.ui.setupUi(self.window, self.ID_Pengguna)
        self.window.show()
        self.PesananKlienWindow.close()
        print("Pesan RS")
        return

    def to_suhu_harian(self):
        # Navigate to suhu harian page
        from Suhu_Klien import Ui_SuhuKlienWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SuhuKlienWindow()
        self.ui.setupUi(self.window, self.ID_Pengguna)
        self.window.show()
        self.PesananKlienWindow.close()
        print("Suhu Harian")
        return

if __name__ == "__main__":
    import sys
    InitDB()
    app = QtWidgets.QApplication(sys.argv)
    PesananKlienWindow = QtWidgets.QMainWindow()
    ui = Ui_PesananKlienWindow()
    ui.setupUi(PesananKlienWindow)
    PesananKlienWindow.show()
    sys.exit(app.exec_())
